// =============================================================================
// App.java — Application Entry Point
// =============================================================================
// This is a minimal Java class included for completeness. In a real-world
// application, this would contain business logic, REST controllers, or
// service classes.
//
// For this learning project, the primary output is the index.jsp page.
// This class exists so that:
//   1. Maven has Java source code to compile (validates the build process)
//   2. Unit tests have something to test (validates the test phase)
// =============================================================================

package com.devops.app;

/**
 * Main application class for the Pipeline to Actions web app.
 * 
 * In the original CodePipeline project, this was auto-generated by Maven's
 * archetype:generate command. Here we create it manually to understand
 * every piece of the project.
 */
public class App {

    /**
     * Returns a greeting message.
     * This method exists to demonstrate that Java code compiles correctly
     * and can be tested by JUnit in the CI pipeline.
     *
     * @return A greeting string confirming the app is working
     */
    public String getGreeting() {
        return "Pipeline to Actions is running!";
    }

    /**
     * Application entry point (not used by Tomcat, but useful for local testing).
     * 
     * @param args Command-line arguments (not used)
     */
    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
    }
}

